### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by gedw99** [acaloiaro/hugo-htmx-go-template#4]
hey @acaloiaro 

I am thinking about the best way to add Navigation

Have 2 use cases:

- static nav, like you typically se at the bottom of a web site.
- dynamic nav, like a side nav which changes based on other users session ( like what they have access to read, write etc).

If you have any thoughts on this and / or any roadmap things it would be great, so i can contribute.

**Comment by acaloiaro** [comment]
I have some hesitation about adding navigation. The reason being is that the more that one does to edit any specific theme and give it more functionality specific to this project, the harder it is to use this project as a template with _other_ themes that are unedited. The edited theme becomes a golden goose. 

So I guess you could say that one roadmap type item it to make it so that it's easy to apply this project's changes to _any_ theme. 

E.g. in `bin/fetch-deps.sh` we have 

```bash
echo '<script type="text/javascript"src="/htmx.js"></script>' > themes/ananke/layouts/partials/site-scripts.html
```

This ensures that htmx is automatically added to the `ananke` theme's included scripts as part of the "getting started" process. 

This modification is somewhat specific to `ananke` because not all themes have a `site-scripts.html`. So this specific mod can't be done exactly in this way to other themes. Theme-specific changes need to be minimized and/or automated. 

Add nav would have to done similarly.  

I'm not a Hugo expert. If there's a way to add nav in a generalized way that is not tied to the current theme, it would be a nice way of letting the user navigate between the example pages.

**Comment by gedw99** [comment]
just playing around with menu, which is the HUGO name for nav.

 i copied some of the .md from the ./themes/ananke/exampleSite/content up to the ./content

<img width="1280" alt="Screenshot 2023-07-08 at 10 51 11" src="https://github.com/acaloiaro/hugo-htmx-go-template/assets/53147028/7d067bbc-e361-48b6-852d-5907346b2db4">

So looks like static nav works. 
I am not sure at the moment, but  maybe it is possible to add nav that is a Partial and so can follow the same pattern you already used. 

--

I then added the EN / FR content and updated the the config.

It got messed up. Hugo is a mystery sometimes.

**Comment by gedw99** [comment]
<img width="1280" alt="Screenshot 2023-07-08 at 11 23 00" src="https://github.com/acaloiaro/hugo-htmx-go-template/assets/53147028/d3cd4b5b-c6c6-4915-ad9c-6258ac0147ee">

the partials done seem to like the multi language.

**Comment by acaloiaro** [comment]
While I'd love to help people build all sorts of things with this project as the template, I think this nav idea might be a bit too prescriptive and theme-specific. 

If dynamic nav can be achieved in a theme-agnostic way, I think it would be a great thing to add. Because I'm not aware of how (or if it's possible) to do that, I'll have to defer to you or others to be the ones who bring a solution to the table.

**Comment by gedw99** [comment]
What I started worked. Just not expert in Hugo.
